app/models.py
from flask import current_app
from flask_login import UserMixin
from itsdangerous import URLSafeTimedSerializer
from werkzeug.security import generate_password_hash, check_password_hash

from . import db
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    dues = db.relationship("Due", foreign_keys="Due.owner_id", backref="owner")
    password_hash = db.Column(db.String(128))

    def generate_registration_token(self):
        s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
        return s.dumps(self.id)

    @property
    def password(self):
        raise AttributeError("password is not a readble attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self): 
        return "<User %s (%s)>" % (self.id, self.name)

class Purchase(db.Model):
    __tablename__ = "purchases"
    id = db.Column(db.Integer, primary_key=True)
    item = db.Column(db.String(64))
    by_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    by = db.relationship("User")
    split = db.Column(db.Integer)
    price = db.Column(db.Float)

    def __repr__(self):
        return "<Purchase %s (%s, %s, %s)>" % (self.id, self.item, self.by.name, self.price)

class Due(db.Model):
    __tablename__ = "dues"
    owner_id = db.Column(db.Integer, db.ForeignKey("users.id"), primary_key=True)
    to_id = db.Column(db.Integer, db.ForeignKey("users.id"), primary_key=True)
    to = db.relationship("User", foreign_keys="Due.to_id")
    amount = db.Column(db.Integer)

    def __repr__(self):
        return "<Due %s, %s (%s)>" % (self.owner_id, self.to_id, self.amount)

app/main/forms.py
import math

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, SelectMultipleField, BooleanField
from wtforms.validators import Required, ValidationError, EqualTo, Regexp

from ..models import User

class AddPurchaseForm(FlaskForm):
    def number_check(form, field):
        try: 
            number = float(field.data)
        except:
            raise ValidationError("Please enter a number.")
        if math.isinf(number) or math.isnan(number):
            raise ValidationError("Please enter a valid number.")

    item = StringField("Item", validators=[Required()])
    split = SelectMultipleField(coerce=int)
    price = StringField("Price", validators=[Required(), number_check])
    submit = SubmitField("Add purchase")

class LoginForm(FlaskForm):
    name = StringField("Name", validators=[Required()])
    password = PasswordField("Password", validators=[Required()])
    remember_me = BooleanField("Keep me logged in")
    submit = SubmitField("Log in")

class RegistrationForm(FlaskForm):
    name = StringField("Name", validators=[Required(), Regexp(r"^[A-Za-z]+$", message="Username must only have letters.")])
    password = PasswordField("Password", validators=[Required()])
    confirm = PasswordField("Confirm password", validators=[Required(), EqualTo("password", message="Passwords must match.")])
    submit = SubmitField("Create account")

    def validate_name(self, field):
        if User.query.filter_by(name=field.data).first():
            raise ValidationError("Name is already in use.")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "main.login"

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views

app/main/views.py
import math

from flask import current_app, flash, url_for, redirect, render_template, request
from flask_login import login_user, logout_user, login_required, current_user
from itsdangerous import URLSafeTimedSerializer

from . import main
from .. import db
from ..models import User, Due, Purchase
from .forms import RegistrationForm, LoginForm, AddPurchaseForm

@main.route("/register/<token>", methods=["POST","GET"])
def register(token):
    s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
    try:
        id = s.loads(token, max_age=86400)
    except:
        flash("The registration link is invalid or has expired")
        return redirect(url_for("main.index"))

    u = User.query.get(id)
    if u.name and u.password_hash:
        flash("User is already registered.")
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        u.name = form.name.data
        u.password = form.password.data
        db.session.add(u)
        db.session.commit()
        flash("User registration successful.")
        return redirect(url_for("main.index"))
    return render_template("quick_form.html", header="Register", form=form)

@main.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.name.ilike(form.name.data)).first()
        print(form.name.data)
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get("next") or url_for("main.index"))
        flash("Invalid username or password.")
    return render_template("quick_form.html", header="Log in", form=form)

@main.route("/logout")
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))

def update_dues(p, split):
    if split:
        split_list = [User.query.get(id) for id in split]
        split_price = p.price/(len(split_list)+1)
    else:
        split_list = User.query.filter(User.name != p.by.name).all()
        split_price = p.price/User.query.count()
    for to_user in split_list:
        forward = Due.query.filter_by(owner_id=to_user.id, to_id=current_user.id).first()
        if not forward:
            forward = Due(owner=to_user,to=current_user, amount=0)
        backward = Due.query.filter_by(owner_id=current_user.id, to_id=to_user.id).first()
        if not backward:
            backward = Due(owner=current_user,to=to_user, amount=0)
        forward.amount += split_price
        m = min(forward.amount, backward.amount)
        forward.amount -= m
        backward.amount -= m
        db.session.add(forward)
        db.session.add(backward)
    db.session.add(p)
    db.session.commit()

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(error)

@main.route("/", methods=["GET","POST"])
def index():
    form = AddPurchaseForm()
    if current_user.is_authenticated:
        form.split.choices = [(u.id, u.name) for u in User.query.filter(User.name != current_user.name)]
    if form.validate_on_submit():
        split = ", ".join([User.query.get(id).name for id in form.split.data])
        p = Purchase(item=form.item.data, 
                     by=current_user, 
                     split=split if split else "Everyone",
                     price=float(form.price.data))
        update_dues(p, form.split.data)
        form.item.data = ""
        form.split.data = ""
        form.price.data = ""
        #new item add animation
        return redirect(url_for("main.index"))

    flash_errors(form)
    users = User.query.filter(User.name != None).all()
    n_users = len(users)
    n_rows = math.ceil(n_users/3.0)
    return render_template("index.html", purchases=Purchase.query.all(), form=form, n_rows=n_rows, users=users, n_users=n_users)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Ledger{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Ledger</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Dues</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <p class="navbar-text text-muted">Signed in as {{ current_user.name }}</p>
                <li><a href="{{ url_for('main.logout') }}">Sign out</a></li>
                {% else %}
                <li><a href="{{ url_for('main.login') }}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Ledger</h1>
</div>
<table class="table table-bordered table-striped">
    <tr>
        <th>Item</th>
        <th>By</th>
        <th>Split with</th>
        <th>Price</th>
    </tr>
    {% for purchase in purchases %}
    <tr>
        <td>{{ purchase.item }}</td>
        <td>{{ purchase.by.name }}</td>
        <td>{{ purchase.split }}</td>
        <td>${{ "%.2f" % purchase.price }}</td>
    </tr>
    {% endfor %}
</table>

{% if current_user.is_authenticated %}
<form method="POST"  class="form-inline">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.item(class="form-control", placeholder="Item name", required=True) }}
    </div>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">$</div>
            {{ form.price(class="form-control", placeholder="Price", required=True) }}
        </div>
    </div>
    <div class="form-group" >
        {{ form.split(**{"class": "selectpicker", "title": "Split with everyone", "data-max-options": "1"}) }}
        <span class="glyphicon glyphicon-question-sign" 
        title="Select the people to split the purchase with. Select none to split with everyone."></span>
    </div>
    {{ form.submit(class="btn btn-primary") }}
</form>
{% endif %}

<div class="page-header">
    <h1>Dues</h1>
</div>

{% for i in range(n_rows) %}
    {% for j in range(3) %}
<div class="col-md-4">
        {% if 3*i+j < n_users %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ users[3*i+j].name }}</h3>
            </div>
            <table class="table">
                <tr>
                    <th>Person</th>
                    <th>Amount</th>
                </tr>
                {% for due in users[3*i+j].dues %}
                <tr>
                    <td>{{ due.to.name }}</td>
                    <td>${{ "%.2f" % due.amount }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
</div>
    {% endfor %}
{% endfor %}
{% endblock %}

app/templates/quick_form.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class=page-header>
    <h1>{{ header }}</h1>
</div>
<div class=col-md-4>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Ledger{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('index') }}">Ledger</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('index') }}">Dues</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <p class="navbar-text text-muted">Signed in as {{ current_user.name }}</p>
                <li><a href="{{ url_for('logout') }}">Sign out</a></li>
                {% else %}
                <li><a href="{{ url_for('login') }}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class=page-header>
    <h1>Sign in</h1>
</div>
<div class=col-md-4>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}